org: kidtango
app: appsync-master-class
service: appsync-master-class

frameworkVersion: '2'

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

package:
  exclude:
    - package.json
    - package-lock.json