org: kidtango
app: appsync-master-class
service: appsync-master-class

frameworkVersion: '2'

custom:
  tableName: 'users-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  stage: dev
functions:
  api:
    handler: handler.handler